bitgroom filter is available for encoding and decoding.
....Create dataset ................
....Writing bitgroom filtered data ................
....Close the file and reopen for reading ........
Filter info is available from the dataset creation property
   Filter identifier is 32008
   Number of parameters is 6 with the value 0
   To find more about the filter check bitgroom; see https://github.com/kiyo-masui/bitgroom
....Reading bitgroom filtered data ................
Maximum value in DS1 is 1890
bitgroom filter is available now since H5Dread triggered loading of the filter.
