SZ filter is available for encoding and decoding.
....Create dataset ................
....Writing SZ compressed data ................
....Close the file and reopen for reading ........
Filter info is available from the dataset creation property
   Filter identifier is 32017
   Number of parameters is 14 with the value 3
   To find more about the filter check SZ compressor/decompressor for floating-point data.
....Reading SZ compressed data ................
Maximum value in DS1 is 8190.8975
SZ filter is available now since H5Dread triggered loading of the filter.
