Zstandard filter is available for encoding and decoding.
....Create dataset ................
....Writing Zstandard-compressed data ................
....Close the file and reopen for reading ........
Filter info is available from the dataset creation property 
   Filter identifier is 32015
   Number of parameters is 1 with the value 3
   To find more about the filter check Zstandard filter for HDF5; http://www.zstd.net
....Reading Zstandard-compressed data ................
Maximum value in DS1 is 1890
Zstandard filter is available now since H5Dread triggered loading of the filter.
