name: hdf5 plugins daily build

on:
  workflow_dispatch:
    inputs:
      use_ignore:
        description: 'Ignore has changes check'
        type: string
        required: false
        default: check
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel.
jobs:
  get-old-names:
    runs-on: ubuntu-latest
    outputs:
      hdf5-name: ${{ steps.gethdf5base.outputs.HDF5_NAME_BASE }}
      plugin-name: ${{ steps.getpluginbase.outputs.PLUGIN_NAME_BASE }}
      run-ignore: ${{ steps.getinputs.outputs.INPUTS_IGNORE }}

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Get hdf5 release base name
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'HDFGroup/hdf5'
        version: 'tags/snapshot-1.14'
        file: 'last-file.txt'

    - name: Read HDF5 base-name file
      id: gethdf5base
      run: echo "HDF5_NAME_BASE=$(cat last-file.txt)" >> $GITHUB_OUTPUT

    - run: echo "hdf5 base name is ${{ steps.gethdf5base.outputs.HDF5_NAME_BASE }}."

    - name: Get plugin release base name
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: 'HDFGroup/hdf5_plugins'
        version: 'tags/snapshot-1.14'
        file: 'last-file.txt'

    - name: Read base-name file
      id: getpluginbase
      run: echo "PLUGIN_NAME_BASE=$(cat last-file.txt)" >> $GITHUB_OUTPUT

    - run: echo "plugin base name is ${{ steps.getpluginbase.outputs.PLUGIN_NAME_BASE }}."

    - name: Read inputs
      id: getinputs
      run: |
        echo "INPUTS_IGNORE=${{ ((github.event.inputs.use_ignore == '' && github.event.inputs.use_ignore)  || 'ignore') }}" >> $GITHUB_OUTPUT

    - run: echo "use_ignore is ${{ steps.getinputs.outputs.INPUTS_IGNORE }}."

  call-workflow-tarball:
    needs: [get-old-names]
    uses: ./.github/workflows/tarball.yml
    with:
      use_tag: snapshot-1.14
      use_environ: snapshots

  call-workflow-ctest:
    needs: [get-old-names, call-workflow-tarball]
    uses: ./.github/workflows/cmake-ctest.yml
    with:
      preset_name: ci-StdShar
      file_base: ${{ needs.call-workflow-tarball.outputs.file_base }}
      use_hdf: ${{ needs.get-old-names.outputs.hdf5-name }}
#      use_tag: snapshot-1.14
      use_environ: snapshots
    if: ${{ ((needs.call-workflow-tarball.outputs.has_changes == 'true') || (needs.get-base-names.outputs.run-ignore == 'ignore')) }}

  call-workflow-release:
    needs: [get-old-names, call-workflow-tarball, call-workflow-ctest]
    permissions:
      contents: write # In order to allow tag creation
    uses: ./.github/workflows/release-files.yml
    with:
      file_base: ${{ needs.call-workflow-tarball.outputs.file_base }}
      file_branch: ${{ needs.call-workflow-tarball.outputs.file_branch }}
      file_sha: ${{ needs.call-workflow-tarball.outputs.file_sha }}
      use_tag: snapshot-1.14
      use_environ: snapshots
    if: ${{ ((needs.call-workflow-tarball.outputs.has_changes == 'true') || (needs.get-base-names.outputs.run-ignore == 'ignore')) }}

  call-workflow-remove:
    needs: [get-old-names, call-workflow-tarball, call-workflow-ctest, call-workflow-release]
    permissions:
      contents: write # In order to allow file deletion
    uses: ./.github/workflows/remove-files.yml
    with:
      file_base: ${{ needs.get-old-names.outputs.plugin-name }}
      use_tag: snapshot-1.14
      use_environ: snapshots
    if: ${{ ((needs.call-workflow-tarball.outputs.has_changes == 'true') || (needs.get-base-names.outputs.run-ignore == 'ignore')) }}

