name: HDF5 plugins testing with package managers on MacOS

on:
  workflow_call:
    inputs:
      build_mode:
        description: "Build type (CMAKE_BUILD_TYPE)"
        required: true
        type: string
      hdf5_tag:
        description: "HDF5 git tag to use"
        required: false
        default: "develop"
        type: string
      zlib_type:
        description: "Type of zlib to use ('zlib' (default) or 'zlib-ng')"
        required: false
        default: "zlib"
        type: string

permissions:
  contents: read

jobs:
  # Install and test against filter libraries that are available from homebrew.
  # Currently installs and tests against the following filters:
  #   - Blosc2
  #   - JPEG
  #   - Zstandard
  #
  # The following filters are not yet tested against due to either missing packages or
  # lack of ability for CMake to find the installed packages currently (CMake doesn't
  # include a module for finding the package and the package doesn't include a CMake
  # configuration file):
  #   - Bitgroom
  #   - Bitround
  #   - Bitshuffle
  #   - Blosc
  #   - Bzip2
  #   - LZ4
  #   - LZF
  #   - ZFP
  #
  # No special testing of libaec and zlib(-ng) is currently performed, but they
  # are installed and HDF5 is built with them. It is assumed that testing with
  # libaec and zlib(-ng) is performed in the HDF5 repository instead.
  build_and_test:
    name: "MacOS Clang"
    runs-on: macos-latest
    steps:
      - name: Install filter libraries
        run: |
          #brew install c-blosc
          brew install c-blosc2
          #brew install bzip2
          brew install libaec
          brew install jpeg
          #brew install lz4
          brew install zstd

      - name: Install zlib
        if: ${{ inputs.zlib_type == 'zlib' }}
        run: brew install zlib

      - name: Install zlib-ng
        if: ${{ inputs.zlib_type == 'zlib-ng' }}
        run: brew install zlib-ng

      - name: Get sources for HDF5 plugins project
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Get sources for HDF5
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          repository: HDFGroup/hdf5
          ref: "${{ inputs.hdf5_tag }}"
          path: ${{ github.workspace }}/hdf5

      - name: Set zlib-ng option
        id: set_zlibng_option
        run: |
          if test "${{ inputs.zlib_type }}" = "zlib-ng"; then
            echo "zlibng_option=ON" >> "$GITHUB_OUTPUT"
          else
            echo "zlibng_option=OFF" >> "$GITHUB_OUTPUT"
          fi

      - name: Build HDF5
        shell: bash
        run: |
          cd "${{ github.workspace }}/hdf5"
          mkdir build
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=${{ inputs.build_mode }} \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/hdf5_build" \
            -DBUILD_STATIC_LIBS=OFF \
            -DBUILD_TESTING=OFF \
            -DHDF5_ENABLE_ZLIB_SUPPORT=ON \
            -DHDF5_ENABLE_SZIP_SUPPORT=ON \
            -DHDF5_USE_ZLIB_NG=${{ steps.set_zlibng_option.outputs.zlibng_option }} \
            ..
          cmake --build . --parallel 3 --config ${{ inputs.build_mode }}
          cmake --install . --config ${{ inputs.build_mode }}

      - name: Build HDF5 plugins project
        shell: bash
        run: |
          mkdir "${{ runner.workspace }}/build"
          cd "${{ runner.workspace }}/build"
          cmake \
            -DCMAKE_BUILD_TYPE=${{ inputs.build_mode }} \
            -DHDF5_DIR="${{ github.workspace }}/hdf5_build/cmake" \
            -DH5PL_BUILD_TESTING=ON \
            -DH5PL_BUILD_EXAMPLES=ON \
            -DENABLE_BLOSC=OFF \
            -DENABLE_BLOSC2=ON \
            -DENABLE_BZIP2=OFF \
            -DENABLE_JPEG=ON \
            -DENABLE_LZ4=OFF \
            -DENABLE_LZF=OFF \
            -DENABLE_ZFP=OFF \
            -DENABLE_ZSTD=ON \
            -DENABLE_BITGROOM=OFF \
            -DENABLE_BITROUND=OFF \
            -DENABLE_BSHUF=OFF \
            $GITHUB_WORKSPACE
          cmake --build . --parallel 3 --config ${{ inputs.build_mode }}

      - name: Test HDF5 plugins project
        shell: bash
        run: |
          cd "${{ runner.workspace }}/build"
          ctest . --output-on-failure --parallel 3 -C ${{ inputs.build_mode }}
