name: HDF5 plugins testing with CMake FetchContent on Ubuntu

on:
  workflow_call:
    inputs:
      build_mode:
        description: "Build type (CMAKE_BUILD_TYPE)"
        required: true
        type: string
      hdf5_tag:
        description: "HDF5 git tag to use"
        required: false
        default: "develop"
        type: string
      zlib_type:
        description: "Type of zlib to use ('zlib' (default) or 'zlib-ng')"
        required: false
        default: "zlib"
        type: string

permissions:
  contents: read

jobs:
  # Test building filter libraries and hdf5_plugins project inline with CMake's
  # FetchContent (git) functionality while building HDF5.
  build_and_test_inline:
    name: "Ubuntu GCC (hdf5_plugins built inline with HDF5)"
    runs-on: ubuntu-latest
    steps:
      - name: Get sources for HDF5
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          repository: HDFGroup/hdf5
          ref: "${{ inputs.hdf5_tag }}"
          path: ${{ github.workspace }}/hdf5

      - name: Set zlib-ng option
        id: set_zlibng_option
        run: |
          if test "${{ inputs.zlib_type }}" = "zlib-ng"; then
            echo "zlibng_option=ON" >> "$GITHUB_OUTPUT"
            echo "zlib_external=ON" >> "$GITHUB_OUTPUT"
          else
            echo "zlibng_option=OFF" >> "$GITHUB_OUTPUT"
            echo "zlib_external=OFF" >> "$GITHUB_OUTPUT"
          fi
 
      # TODO: Re-enable ZSTD testing after CMake logic issue is fixed
      - name: Build HDF5 and HDF5 plugins
        run: |
          cd ${{ github.workspace }}/hdf5
          mkdir build
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=${{ inputs.build_mode }} \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/hdf5_build \
            -DBUILD_STATIC_LIBS=OFF \
            -DHDF5_ALLOW_EXTERNAL_SUPPORT=GIT \
            -DHDF5_ENABLE_ZLIB_SUPPORT=OFF \
            -DZLIB_USE_EXTERNAL=${{ steps.set_zlibng_option.outputs.zlib_external }} \
            -DHDF5_USE_ZLIB_NG=${{ steps.set_zlibng_option.outputs.zlibng_option }} \
            -DHDF5_ENABLE_SZIP_SUPPORT=ON \
            -DSZIP_USE_EXTERNAL=ON \
            -DHDF5_ENABLE_PLUGIN_SUPPORT=ON \
            -DPLUGIN_USE_EXTERNAL=ON \
            -DPLUGIN_USE_LOCALCONTENT=OFF \
            -DH5PL_ALLOW_EXTERNAL_SUPPORT=GIT \
            -DH5PL_BUILD_TESTING=ON \
            -DH5PL_BUILD_EXAMPLES=ON \
            -DENABLE_BLOSC=ON \
            -DENABLE_BLOSC2=ON \
            -DENABLE_BZIP2=ON \
            -DENABLE_JPEG=ON \
            -DENABLE_LZ4=ON \
            -DENABLE_LZF=ON \
            -DENABLE_ZFP=ON \
            -DENABLE_ZSTD=OFF \
            -DENABLE_BITGROOM=ON \
            -DENABLE_BITROUND=ON \
            -DENABLE_BSHUF=ON \
            ..
          # NOTE: Currently a serial build has to be forced, as Blosc and Blosc2
          # appear to have a parallel building dependency issue
          cmake --build . --parallel 1 --config ${{ inputs.build_mode }}
          cmake --install . --config ${{ inputs.build_mode }}

      - name: Test HDF5 and HDF5 plugins
        shell: bash
        run: |
          cd "${{ github.workspace }}/hdf5/build"
          ctest . --output-on-failure --parallel 4 -C ${{ inputs.build_mode }}

  # Test building hdf5_plugins project against an already-installed HDF5. Filter
  # libraries are built with FetchContent (git) while building hdf5_plugins.
  build_and_test_git:
    name: "Ubuntu GCC (hdf5_plugins built standalone; plugins built via git)"
    runs-on: ubuntu-latest
    steps:
      - name: Get sources for HDF5 plugins project
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Get sources for HDF5
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          repository: HDFGroup/hdf5
          ref: "${{ inputs.hdf5_tag }}"
          path: ${{ github.workspace }}/hdf5

      - name: Set zlib-ng option
        id: set_zlibng_option
        run: |
          if test "${{ inputs.zlib_type }}" = "zlib-ng"; then
            echo "zlibng_option=ON" >> "$GITHUB_OUTPUT"
          else
            echo "zlibng_option=OFF" >> "$GITHUB_OUTPUT"
          fi

      - name: Build HDF5
        run: |
          cd ${{ github.workspace }}/hdf5
          mkdir build
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=${{ inputs.build_mode }} \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/hdf5_build \
            -DBUILD_STATIC_LIBS=OFF \
            -DHDF5_ALLOW_EXTERNAL_SUPPORT=GIT \
            -DHDF5_ENABLE_ZLIB_SUPPORT=ON \
            -DZLIB_USE_EXTERNAL=ON \
            -DHDF5_USE_ZLIB_NG=${{ steps.set_zlibng_option.outputs.zlibng_option }} \
            -DHDF5_ENABLE_SZIP_SUPPORT=ON \
            -DSZIP_USE_EXTERNAL=ON \
            ..
          cmake --build . --parallel 4 --config ${{ inputs.build_mode }}
          cmake --install . --config ${{ inputs.build_mode }}

      - name: Build HDF5 plugins project
        run: |
          mkdir "${{ runner.workspace }}/build"
          cd "${{ runner.workspace }}/build"
          cmake \
            -DCMAKE_BUILD_TYPE=${{ inputs.build_mode }} \
            -DHDF5_DIR=${{ github.workspace }}/hdf5_build/cmake \
            -DH5PL_ALLOW_EXTERNAL_SUPPORT=GIT \
            -DH5PL_BUILD_TESTING=ON \
            -DH5PL_BUILD_EXAMPLES=ON \
            -DENABLE_BLOSC=ON \
            -DENABLE_BLOSC2=ON \
            -DENABLE_BZIP2=ON \
            -DENABLE_JPEG=ON \
            -DENABLE_LZ4=ON \
            -DENABLE_LZF=ON \
            -DENABLE_ZFP=ON \
            -DENABLE_ZSTD=ON \
            -DENABLE_BITGROOM=ON \
            -DENABLE_BITROUND=ON \
            -DENABLE_BSHUF=ON \
            $GITHUB_WORKSPACE
          # NOTE: Currently, a serial build has to be forced as Blosc and Blosc2
          # appear to have a parallel building dependency issue
          cmake --build . --parallel 1 --config ${{ inputs.build_mode }}

      - name: Test HDF5 plugins project
        run: |
          cd "${{ runner.workspace }}/build"
          ctest . --output-on-failure --parallel 4 -C ${{ inputs.build_mode }}

  # Test building hdf5_plugins project against an already-installed HDF5. Filter
  # libraries are built with FetchContent (tgz) while building hdf5_plugins.
  build_and_test_tgz:
    name: "Ubuntu GCC (hdf5_plugins built standalone; plugins built via tgz)"
    runs-on: ubuntu-latest
    steps:
      - name: Get sources for HDF5 plugins project
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Get sources for HDF5
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          repository: HDFGroup/hdf5
          ref: "${{ inputs.hdf5_tag }}"
          path: ${{ github.workspace }}/hdf5

      - name: Set zlib-ng option
        id: set_zlibng_option
        run: |
          if test "${{ inputs.zlib_type }}" = "zlib-ng"; then
            echo "zlibng_option=ON" >> "$GITHUB_OUTPUT"
          else
            echo "zlibng_option=OFF" >> "$GITHUB_OUTPUT"
          fi

      - name: Build HDF5
        run: |
          cd ${{ github.workspace }}/hdf5
          mkdir build
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=${{ inputs.build_mode }} \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/hdf5_build \
            -DBUILD_STATIC_LIBS=OFF \
            -DHDF5_ALLOW_EXTERNAL_SUPPORT=TGZ \
            -DHDF5_ENABLE_ZLIB_SUPPORT=ON \
            -DZLIB_USE_EXTERNAL=ON \
            -DZLIB_USE_LOCALCONTENT=OFF \
            -DHDF5_USE_ZLIB_NG=${{ steps.set_zlibng_option.outputs.zlibng_option }} \
            -DHDF5_ENABLE_SZIP_SUPPORT=ON \
            -DSZIP_USE_EXTERNAL=ON \
            -DLIBAEC_USE_LOCALCONTENT=OFF \
            ..
          cmake --build . --parallel 4 --config ${{ inputs.build_mode }}
          cmake --install . --config ${{ inputs.build_mode }}

      - name: Build HDF5 plugins project
        run: |
          mkdir "${{ runner.workspace }}/build"
          cd "${{ runner.workspace }}/build"
          cmake \
            -DCMAKE_BUILD_TYPE=${{ inputs.build_mode }} \
            -DHDF5_DIR=${{ github.workspace }}/hdf5_build/cmake \
            -DH5PL_ALLOW_EXTERNAL_SUPPORT=TGZ \
            -DH5PL_BUILD_TESTING=ON \
            -DH5PL_BUILD_EXAMPLES=ON \
            -DENABLE_BLOSC=ON \
            -DENABLE_BLOSC2=ON \
            -DENABLE_BZIP2=ON \
            -DENABLE_JPEG=ON \
            -DENABLE_LZ4=ON \
            -DENABLE_LZF=ON \
            -DENABLE_ZFP=ON \
            -DENABLE_ZSTD=ON \
            -DENABLE_BITGROOM=ON \
            -DENABLE_BITROUND=ON \
            -DENABLE_BSHUF=ON \
            $GITHUB_WORKSPACE
          # NOTE: Currently, a serial build has to be forced as Blosc and Blosc2
          # appear to have a parallel building dependency issue
          cmake --build . --parallel 1 --config ${{ inputs.build_mode }}

      - name: Test HDF5 plugins project
        run: |
          cd "${{ runner.workspace }}/build"
          ctest . --output-on-failure --parallel 4 -C ${{ inputs.build_mode }}
