name: hdf5 plugins publish release

# Triggers the workflow on demand
on:
  workflow_dispatch:
    inputs:
      use_tag:
        description: 'HDF5 Plugins Release version tag'
        type: string
        required: true
      target_dir:
        description: 'HDF5 Plugins target bucket directory'
        type: string
        required: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read

jobs:
  publish-tag:
    runs-on: ubuntu-latest
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Get Sources
          uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
          with:
            fetch-depth: 0
            ref: '${{ github.head_ref || github.ref_name }}'

        - name: Get plugins release
          uses: robinraju/release-downloader@v1
          with:
            repository: 'HDFGroup/hdf5_plugins'
            tag: '${{ inputs.use_tag }}'
            fileName: '${{ inputs.use_tag }}-*.*'
            out-file-path: 'PLUGINS'
            token: ${{ github.token }}

        - name: Setup AWS CLI
          uses: aws-actions/configure-aws-credentials@v6
          with:
                 aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                 aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                 aws-region: ${{ secrets.AWS_REGION }}

        - name: Sync release to S3 bucket
          run: |
                aws s3 sync ./PLUGINS s3://${{ secrets.AWS_S3_BUCKET }}/${{ vars.TARGET_PATH }}/${{ inputs.target_dir }}/downloads/plugins --delete

