szf filter is available for encoding and decoding.
....Create dataset ................
....Writing szf compressed data ................
....Close the file and reopen for reading ........
Filter info is available from the dataset creation property
   Filter identifier is 32017
   Number of parameters is 5 with the value 3
   To find more about the filter check SZ compressor/decompressor for floating-point data.
....Reading szf compressed data ................
Maximum value in DS1 is 18446744073709551616.000000
szf filter is available now since H5Dread triggered loading of the filter.
